# -*- coding: utf-8 -*-
"""Advanced Time Series Forecasting with Seq2Seq + Attention.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ezmym7ef_JQmvfBLFgwyWOOqvwuCA01t
"""

# ============================================================
# Advanced Time Series Forecasting with Seq2Seq + Attention
# ============================================================

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, Dataset
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error
from statsmodels.tsa.arima.model import ARIMA
import random

# -----------------------------
# Reproducibility
# -----------------------------
SEED = 42
np.random.seed(SEED)
torch.manual_seed(SEED)
random.seed(SEED)

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

# -----------------------------
# 1. Data Generation
# -----------------------------
def generate_multivariate_series(n_steps=1500, n_features=5):
    t = np.arange(n_steps)
    data = []

    for i in range(n_features):
        signal = np.sin(0.01 * t + i) + 0.5 * np.sin(0.03 * t)
        noise = np.random.normal(0, 0.3, n_steps)
        data.append(signal + noise)

    return np.stack(data, axis=1)

# -----------------------------
# 2. Dataset + Preprocessing
# -----------------------------
class TimeSeriesDataset(Dataset):
    def __init__(self, data, input_len, output_len):
        self.X, self.y = [], []
        for i in range(len(data) - input_len - output_len):
            self.X.append(data[i:i+input_len])
            self.y.append(data[i+input_len:i+input_len+output_len, 0])
        self.X = torch.tensor(self.X, dtype=torch.float32)
        self.y = torch.tensor(self.y, dtype=torch.float32)

    def __len__(self):
        return len(self.X)

    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]

# -----------------------------
# 3. Seq2Seq + Bahdanau Attention
# -----------------------------
class Encoder(nn.Module):
    def __init__(self, input_dim, hidden_dim):
        super().__init__()
        self.lstm = nn.LSTM(input_dim, hidden_dim, batch_first=True)

    def forward(self, x):
        outputs, (h, c) = self.lstm(x)
        return outputs, h, c


class BahdanauAttention(nn.Module):
    def __init__(self, hidden_dim):
        super().__init__()
        self.W1 = nn.Linear(hidden_dim, hidden_dim)
        self.W2 = nn.Linear(hidden_dim, hidden_dim)
        self.V = nn.Linear(hidden_dim, 1)

    def forward(self, encoder_outputs, hidden):
        hidden = hidden.permute(1, 0, 2)
        score = self.V(torch.tanh(
            self.W1(encoder_outputs) + self.W2(hidden)
        ))
        weights = torch.softmax(score, dim=1)
        context = torch.sum(weights * encoder_outputs, dim=1)
        return context


class Decoder(nn.Module):
    def __init__(self, hidden_dim, output_len):
        super().__init__()
        self.attn = BahdanauAttention(hidden_dim)
        self.lstm = nn.LSTM(hidden_dim + 1, hidden_dim, batch_first=True)
        self.fc = nn.Linear(hidden_dim, 1)
        self.output_len = output_len

    def forward(self, encoder_outputs, h, c):
        batch_size = encoder_outputs.size(0)
        outputs = []
        input_step = torch.zeros(batch_size, 1, 1).to(DEVICE)

        for _ in range(self.output_len):
            context = self.attn(encoder_outputs, h)
            context = context.unsqueeze(1)
            lstm_input = torch.cat([input_step, context], dim=2)
            out, (h, c) = self.lstm(lstm_input, (h, c))
            pred = self.fc(out)
            outputs.append(pred.squeeze(1))
            input_step = pred.detach()

        return torch.cat(outputs, dim=1)


class Seq2Seq(nn.Module):
    def __init__(self, input_dim, hidden_dim, output_len):
        super().__init__()
        self.encoder = Encoder(input_dim, hidden_dim)
        self.decoder = Decoder(hidden_dim, output_len)

    def forward(self, x):
        enc_out, h, c = self.encoder(x)
        return self.decoder(enc_out, h, c)

# -----------------------------
# 4. Training Utilities
# -----------------------------
def train_model(model, loader, epochs=15, lr=0.001):
    model.train()
    optimizer = torch.optim.Adam(model.parameters(), lr=lr)
    loss_fn = nn.MSELoss()

    for epoch in range(epochs):
        total_loss = 0
        for X, y in loader:
            X, y = X.to(DEVICE), y.to(DEVICE)
            optimizer.zero_grad()
            preds = model(X)
            loss = loss_fn(preds, y)
            loss.backward()
            optimizer.step()
            total_loss += loss.item()

        print(f"Epoch {epoch+1}/{epochs} - Loss: {total_loss/len(loader):.4f}")

# -----------------------------
# 5. Evaluation
# -----------------------------
def evaluate(model, loader):
    model.eval()
    preds, actuals = [], []

    with torch.no_grad():
        for X, y in loader:
            X = X.to(DEVICE)
            out = model(X)
            preds.append(out.cpu().numpy())
            actuals.append(y.numpy())

    preds = np.concatenate(preds)
    actuals = np.concatenate(actuals)

    rmse = np.sqrt(mean_squared_error(actuals.flatten(), preds.flatten()))
    mae = mean_absolute_error(actuals.flatten(), preds.flatten())
    return rmse, mae

# -----------------------------
# 6. Main Pipeline
# -----------------------------
if __name__ == "__main__":

    raw_data = generate_multivariate_series()
    scaler = StandardScaler()
    scaled_data = scaler.fit_transform(raw_data)

    INPUT_LEN = 30
    OUTPUT_LEN = 5

    split = int(len(scaled_data) * 0.8)
    train_data = scaled_data[:split]
    test_data = scaled_data[split:]

    train_ds = TimeSeriesDataset(train_data, INPUT_LEN, OUTPUT_LEN)
    test_ds = TimeSeriesDataset(test_data, INPUT_LEN, OUTPUT_LEN)

    train_loader = DataLoader(train_ds, batch_size=32, shuffle=True)
    test_loader = DataLoader(test_ds, batch_size=32)

    model = Seq2Seq(
        input_dim=scaled_data.shape[1],
        hidden_dim=64,
        output_len=OUTPUT_LEN
    ).to(DEVICE)

    print("\nTraining Seq2Seq with Attention...")
    train_model(model, train_loader)

    rmse, mae = evaluate(model, test_loader)
    print(f"\nSeq2Seq + Attention RMSE: {rmse:.4f}")
    print(f"Seq2Seq + Attention MAE : {mae:.4f}")

    # -----------------------------
    # 7. ARIMA Baseline
    # -----------------------------
    print("\nTraining ARIMA baseline...")
    target_series = raw_data[:, 0]
    train_ts = target_series[:split]
    test_ts = target_series[split:]

    arima = ARIMA(train_ts, order=(2,1,2)).fit()
    forecast = arima.forecast(steps=len(test_ts))

    arima_rmse = np.sqrt(mean_squared_error(test_ts, forecast))
    arima_mae = mean_absolute_error(test_ts, forecast)

    print(f"ARIMA RMSE: {arima_rmse:.4f}")
    print(f"ARIMA MAE : {arima_mae:.4f}")